# Generated by Django 5.1.5 on 2025-01-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirations',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='personalityTraits',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('positivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('physicalCharacteristics', models.TextField()),
                ('personalityTraits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.personalitytraits')),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in', models.CharField(max_length=10)),
                ('id_out', models.CharField(max_length=10)),
                ('areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.areas')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.relationshiptype')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('aspirations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aspirations')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.description')),
                ('relationships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.relationships')),
            ],
        ),
    ]
