# Generated by Django 5.1.5 on 2025-03-09 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirations',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='personalityTraits',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('positivity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('occupation', models.CharField(default=None, max_length=100, null=True)),
                ('physicalCharacteristics', models.TextField()),
                ('personalityTraits', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.personalitytraits')),
            ],
        ),
        migrations.CreateModel(
            name='Relationships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in', models.CharField(max_length=10)),
                ('id_out', models.CharField(max_length=10)),
                ('areas', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.areas')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.relationshiptype')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=7, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('aspirations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.aspirations')),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.description')),
                ('relationships', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.relationships')),
            ],
        ),
    ]
