# Generated by Django 5.1.5 on 2025-03-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.AddField(
            model_name='person',
            name='information',
            field=models.JSONField(default=None, null=True),
        ),
    ]
