# Generated by Django 5.1.5 on 2025-01-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
