# Generated by Django 5.1.5 on 2025-03-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_remove_person_description_person_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='aspirations',
        ),
    ]
