# Generated by Django 5.1.5 on 2025-01-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_person_description_alter_person_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aspirations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.aspirations'),
        ),
    ]
