# Generated by Django 5.1.5 on 2025-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_description_personalitytraits'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='occupation',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
